(deftheme dusk
  "Created 2021-12-22.")

(custom-theme-set-faces
 'dusk
 '(default ((t (:width normal :height 180 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :stipple nil :inherit nil))))
 '(default ((t (:background "#282B35" :foreground "White"))))
 '(cursor ((t (:background "#FFFFFF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Helvetica")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "orange"))))
 '(highlight ((t (:background "#919075"))))
 '(region ((t (:background "#555555"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "navy"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#D08E5D"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#54BE5A"))))
 '(font-lock-constant-face ((t (:foreground "#8B86CE"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#95C76E"))))
 '(font-lock-keyword-face ((t (:foreground "#BF369A"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#E1404A"))))
 '(font-lock-type-face ((t (:foreground "#f56dca"))))
 '(font-lock-variable-name-face ((t (:foreground "Yellow"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "Pink"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#536fd6"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "grey10")) (t (:background "gray"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:underline (:color foreground-color :style line) :inverse-video nil)) (((class color grayscale) (background light)) (:box nil :foreground "grey20" :background "grey90")) (((class color grayscale) (background dark)) (:box nil :foreground "grey90" :background "grey20")) (((class mono) (background light)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "black" :background "white")) (((class mono) (background dark)) (:underline (:color foreground-color :style line) :box nil :inverse-video nil :foreground "white" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:underline nil :overline nil :box (:line-width 8 :color "#353644" :style nil) :foreground "white" :background "#353644"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :underline nil :overline nil :box (:line-width 8 :color "#565063" :style nil) :foreground "white" :background "#565063" :inherit (mode-line)))))
 '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(org-document-info ((t (:inherit 'shadow))))
 '(org-document-info-keyword ((t (:foreground "peru"))))
 '(org-document-title ((t (:inherit 'shadow))))
 '(org-level-1 ((t (:inherit 'outline-1))))
 '(org-level-4 ((t (:foreground "SkyBlue2"))))
 '(org-level-5 ((t (:inherit 'org-level-1))))
 '(org-level-6 ((t (:inherit 'org-level-2))))
 '(org-level-7 ((t (:inherit 'org-level-3))))
 '(org-level-8 ((t (:inherit 'org-level-4))))
 '(org-quote-face ((t (:inherit 'org-block))))
 '(org-meta-line ((t (:foreground "peru"))))
 '(org-special-keyword ((t (:inherit 'outline-4))))
 '(org-drawer ((t (:foreground "Gray30"))))
 '(tab-bar ((t (:inherit mode-line))))
 '(tab-bar-tab ((t (:inherit mode-line :foreground "white"))))
 '(tab-bar-tab-inactive ((t (:inherit mode-line-inactive :foreground "black"))))

 ;; Color Meter colors from Terminal
 '(ansi-color-red     ((t (:foreground "#D15C41" :background "#D14C41"))))
 '(ansi-color-green   ((t (:foreground "#70CA50" :background "#70CA50"))))
 '(ansi-color-yellow  ((t (:foreground "#BFBC4f" :background "#BFBC4f"))))
 '(ansi-color-blue    ((t (:foreground "#714ef6" :background "#714ef6"))))
 '(ansi-color-magenta ((t (:foreground "#DB5FE3" :background "#DB5FE3"))))
 '(ansi-color-cyan    ((t (:foreground "#70E7D4" :background "#70E7D4"))))
 '(ansi-color-white   ((t (:foreground "#D5D4D4" :background "#D5D4D4"))))

 '(ansi-color-bright-black   ((t (:foreground "#979797" :background "#979797"))))
 '(ansi-color-bright-red     ((t (:foreground "#EC613F" :background "#EC613F"))))
 '(ansi-color-bright-green   ((t (:foreground "#7BEE55" :background "#7BEE55"))))
 '(ansi-color-bright-yellow  ((t (:foreground "#F1F055" :background "#F1F055"))))
 '(ansi-color-bright-blue    ((t (:foreground "#D19AF9" :background "#D19AF9"))))
 '(ansi-color-bright-magenta ((t (:foreground "#EC61F7" :background "#EC61F7"))))
 '(ansi-color-bright-cyan    ((t (:foreground "#7BF3F4" :background "#7BF3F4"))))
 '(ansi-color-bright-white   ((t (:foreground "#EEEEEE" :background "#EEEEEE"))))

 )

(provide-theme 'dusk)
